stages:
  - deploy

# Master Deploy
deploy:
  stage: deploy
  tags:
    - blue-deploy-shell
  script:
    - 'ssh gitlab-runner@112.124.16.222 << script'
    - 'sh /usr/share/nginx/projects/deploy.sh $CI_PROJECT_NAME /usr/share/nginx/html/chat-tool-bar/$CI_PROJECT_NAME/ "build/*"'
    - 'script'
  only:
    - master@chat-tool-bar/calender-mobile
